src/Entity/Disertante.php
<?php

namespace App\Entity;
use App\Repository\DisertanteRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=App\Repository\DisertanteRepository::class)
 * @ORM\Table(name="disertante")
 */
class Disertante
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apellidos;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $biografia;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $linkedin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evento", mappedBy="disertante")
     */
    private $eventos;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getBiografia(): ?string
    {
        return $this->biografia;
    }

    public function setBiografia(?string $biografia): self
    {
        $this->biografia = $biografia;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getEventos(): Collection {
        return $this->eventos;
    }

    public function getNombreCompleto(){
        return $this->getNombre() . ' ' . $this->getApellidos();
    }

    public function __toString()
    {
        return $this->getNombreCompleto();
    }

    
}

src/Controller/AdminDisertanteController.php
<?php namespace App\Controller;

/* 
  RUTAS:
    /admin/disertante                  --> app_admin_disertante             (opcional, aún no definida)
    /admin/disertante/listado         --> app_admin_disertante_listado     Listar todos los disertantes
    /admin/disertante/nuevo           --> app_admin_disertante_nuevo       Crear nuevo disertante
    /admin/disertante/{id}/editar     --> app_admin_disertante_editar      Editar disertante por ID
    /admin/disertante/{id}/eliminar   --> app_admin_disertante_borrar      Eliminar disertante por ID
*/

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Disertante;
use App\Form\DisertanteType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\DisertanteRepository;

/**
 * @Route("/admin/disertante", name="app_admin_disertante_")
 */
class AdminDisertanteController extends AbstractController
{
  /**
   * @Route("/{id}/editar", name="editar")
   */
  public function editarDisertanteAction(int $id, Request $request, EntityManagerInterface $em): Response
  {
    $disertante = $em->getRepository(Disertante::class)->find($id);

    if (!$disertante) {
      throw $this->createNotFoundException('Disertante no encontrado');
    }

    $form = $this->createForm(DisertanteType::class, $disertante); //Creación del formulario.

    $form->handleRequest($request); //Recibimos las repuestas.

    if ($form->isSubmitted() && $form->isValid()) {
      $em->flush();

      $this->addFlash('success', "El disertante '" . $disertante->getNombreCompleto() . "' se ha actualizado correctamente.");

      return $this->redirectToRoute('app_admin_disertante_listado');
    }

    return $this->render('adminDisertante/editar.html.twig', [
      'form' => $form->createView(),
      'disertante' => $disertante,
    ]);
  }

  /**
   * @Route("/nuevo", name="nuevo")
   */
  public function nuevoDisertanteAction(Request $request): Response
  {
    $disertante = new Disertante();
    $disertante->setNombre('Nombre del disertante');
    $disertante->setEmail('email@ejemplo.com');
    $disertante->setBiografia('Biografía del disertante');

    $form = $this->createForm(DisertanteType::class, $disertante);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $em = $this->getDoctrine()->getManager();
      $em->persist($disertante);
      $em->flush();

      $this->addFlash('info', "El disertante '" . $disertante->getNombre() . "' se ha creado correctamente.");

      return $this->redirectToRoute('app_admin_disertante_listado');
    }

    return $this->render('adminDisertante/nuevo.html.twig', [
      'form' => $form->createView(),
    ]);
  }

  /**
   * @Route("/listado", name="listado")
   */
  public function listadoDisertantes(DisertanteRepository $repository): Response
  {

    $disertantes = $repository->findAll();

    return $this->render('adminDisertante/listado.html.twig', [
      'disertantes' => $disertantes,
    ]);
  }

  /**
   * @Route("/{id}/eliminar", name="borrar")
   */
  public function eliminarDisertanteAction(int $id, EntityManagerInterface $em): Response
  {
    $disertante = $em->getRepository(Disertante::class)->find($id);

    if (!$disertante) {
      throw $this->createNotFoundException('Disertante no encontrado');
    }

    $em->remove($disertante);
    $em->flush();

    $this->addFlash('success', "El disertante '" . $disertante->getNombreCompleto() . "' se ha eliminado correctamente.");

    return $this->redirectToRoute('app_admin_disertante_listado');
  }
}

templates/adminDisertante/editar.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}Editar Disertante{% endblock %}
{% block pageid 'admin' %}

{% block body %}
  <h1>Editar disertante: {{ disertante.nombreCompleto }}</h1>

  {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Actualizar</button>
  {{ form_end(form) }}
{% endblock %}

templates/adminDisertante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdminDisertanteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/cursoSymfony/src/Controller/AdminDisertanteController.php'|file_link(0) }}">src/Controller/AdminDisertanteController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/cursoSymfony/templates/admin_disertante/index.html.twig'|file_link(0) }}">templates/admin_disertante/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/adminDisertante/listado.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}Listado de Disertantes{% endblock %}
{% block pageid 'admin' %}

{% block contenido %}
	<h1>Listado de Disertantes</h1>

	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nombre Completo</th>
				<th>Email</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			{% for disertante in disertantes %}
				<tr>
					<td>{{ disertante.id }}</td>
					<td>{{ disertante.nombreCompleto }}</td>
					<td>{{ disertante.email }}</td>
					<td>
						<a href="{{ path('app_admin_disertante_editar', { id: disertante.id }) }}">Editar</a>
            <a href="{{ path('app_admin_disertante_borrar', { id: disertante.id }) }}">Eliminar</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="4">No hay disertantes registrados.</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_admin_disertante_nuevo') }}" class="button-tag">Nuevo disertante</a>
{% endblock %}

templates/adminDisertante/nuevo.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}Nuevo Disertante{% endblock %}
{% block pageid 'admin' %}

{% block body %}
  {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Guardar</button>
  {{ form_end(form) }}
{% endblock %}